### ISSUE TITLE
Specifying scopes?

### ISSUE THREAD

**Issue by trestrantham** [vinniefranco/ueberauth_fitbit#3]
It seem like this strategy defaults to requesting all available scopes. Is there a way to specify just a subset?

**Comment by vinniefranco** [comment]
Hi there,

You should be able to specify scopes in your Ueberauth config:

``` elixir
config :ueberauth, Ueberauth,
  providers: [
    fitbit: { Ueberauth.Strategy.Fitbit, [default_scope: "activity profile"] }
  ]
```

**Comment by trestrantham** [comment]
Great, thanks! :+1:
